name: 'Install Dependencies'
description: 'Installs dependencies for the project'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash
