name: "Deploy App"
description: "Deploy Python Greetings App using PM2"
inputs:
  env_name:
    description: "Environment name (dev, staging, preprod, prod)"
    required: true
  port:
    description: "Port number for the environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing service
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.env_name }} || true

    - name: Start service with PM2
      working-directory: python-greetings
      run: pm2 start app.py --name greetings-app-${{ inputs.env_name }} -- --port ${{ inputs.port }}
