name: Deploy Service
description: Deploy Python microservice using PM2
inputs:
  environment:
    required: true
  port:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Clone python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop previous service
      run: |
        pm2 delete greetings-app-${{ inputs.environment }} || true
      shell: bash

    - name: Start new service
      run: |
        pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      shell: bash
      working-directory: python-greetings
