name: Deploy Application
description: Deploys the Python service using PM2

inputs:
  environment:
    description: "Deployment environment (dev, staging, preprod, prod)"
    required: true
  port:
    description: "Port number"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing service
      run: pm2 delete greetings-app-${{ inputs.environment }} & EXIT /B 0
      shell: bash
      working-directory: python-greetings

    - name: Start service
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      shell: bash
      working-directory: python-greetings
