name: "Deploy Service"
description: "Deploys the application to a specified environment"

inputs:
  env_name:
    description: "Environment name (dev, staging, preprod, prod)"
    required: true
  port:
    description: "Port number"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Checkout python-greetings repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop old service
      run: pm2 delete greetings-app-${{ inputs.env_name }} || true

    - name: Start new service
      run: pm2 start app.py --name greetings-app-${{ inputs.env_name }} -- --port ${{ inputs.port }}
      working-directory: python-greetings
