name: "Deploy to Environment"
description: "Deploy application to a specific environment"
inputs:
  env_name:
    required: true
    description: "Environment name (dev, staging, preprod, prod)"
  port:
    required: true
    description: "Port number"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing service
      run: pm2 delete greetings-app-${{ inputs.env_name }} || true
      shell: bash

    - name: Start application
      run: pm2 start app.py --name greetings-app-${{ inputs.env_name }} -- --port ${{ inputs.port }}
      shell: bash
      working-directory: python-greetings
