name: "Deploy Service"
description: "Deploys the Python service"
inputs:
  env:
    description: "Deployment environment"
    required: true
  port:
    description: "Port for the service"
    required: true
  working-directory:
    description: "Directory of the application"
    required: true
runs:
  using: "composite"
  steps:
    - name: Stop existing service
      run: pm2 delete greetings-app-${{ inputs.env }} || echo Service not running
      shell: cmd

    - name: Start new service
      run: pm2 start app.py --name greetings-app-${{ inputs.env }} -- --port ${{ inputs.port }}
      shell: cmd
      working-directory: ${{ inputs.working-directory }}
