name: "Install Python Dependencies"
description: "Installs required Python dependencies from requirements.txt"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Clone Python Greetings Repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Install Python Dependencies
      shell: cmd
      working-directory: python-greetings
      run: |
        echo Installing all required dependencies...
        pip install -r requirements.txt
