name: Run Tests
description: Runs API tests using PowerShell
inputs:
  env-name:
    required: true
    description: "Environment name (dev, staging, preprod, prod)"

runs:
  using: "composite"
  steps:
    - name: Checkout test repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/course-js-api-framework
        path: tests

    - name: Install test dependencies
      run: |
        Set-Location -Path "tests"
        npm install
      shell: pwsh

    - name: Run tests
      run: |
        Set-Location -Path "tests"
        npm run greetings greetings_${{ inputs.env-name }}
      shell: pwsh
