name: "Run Tests"
description: "Runs the test suite"
inputs:
  env:
    description: "Test environment"
    required: true
  working-directory:
    description: "Directory of the test framework"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      shell: cmd
      working-directory: ${{ inputs.working-directory }}

    - name: Execute tests
      run: npm run greetings greetings_${{ inputs.env }}
      shell: cmd
      working-directory: ${{ inputs.working-directory }}
