name: Python Greetings Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    uses: ./.github/actions/deploy/action.yml
    with:
      environment: dev
      port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    uses: ./.github/actions/test/action.yml
    with:
      environment: dev

  deploy-to-staging:
    needs: tests-on-dev
    uses: ./.github/actions/deploy/action.yml
    with:
      environment: staging
      port: 7002

  tests-on-staging:
    needs: deploy-to-staging
    uses: ./.github/actions/test/action.yml
    with:
      environment: staging

  deploy-to-preprod:
    needs: tests-on-staging
    uses: ./.github/actions/deploy/action.yml
    with:
      environment: preprod
      port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    uses: ./.github/actions/test/action.yml
    with:
      environment: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    uses: ./.github/actions/deploy/action.yml
    with:
      environment: prod
      port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    uses: ./.github/actions/test/action.yml
    with:
      environment: prod