name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          ref: main
          path: python-greetings

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: python-greetings
        shell: cmd

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop existing app (if running)
        run: |
          pm2 delete greetings-app-dev || echo "No process found"
          exit 0
        shell: cmd

      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          environment: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests on Dev
        uses: ./.github/actions/test
        with:
          environment: dev

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop existing app (if running)
        run: |
          pm2 delete greetings-app-staging || echo "No process found"
          exit 0
        shell: cmd

      - name: Deploy to Staging
        uses: ./.github/actions/deploy
        with:
          environment: staging
          port: 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests on Staging
        uses: ./.github/actions/test
        with:
          environment: staging

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop existing app (if running)
        run: |
          pm2 delete greetings-app-preprod || echo "No process found"
          exit 0
        shell: cmd

      - name: Deploy to Preprod
        uses: ./.github/actions/deploy
        with:
          environment: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests on Preprod
        uses: ./.github/actions/test
        with:
          environment: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop existing app (if running)
        run: |
          pm2 delete greetings-app-prod || echo "No process found"
          exit 0
        shell: cmd

      - name: Deploy to Prod
        uses: ./.github/actions/deploy
        with:
          environment: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests on Prod
        uses: ./.github/actions/test
        with:
          environment: prod
