name: Python Greetings CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v4

      - name: Clone application repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          working-directory: python-greetings

  deploy:
    needs: install-pip-deps
    runs-on: self-hosted
    strategy:
      matrix:
        env: [dev, staging, preprod, prod]
        port: [7001, 7002, 7003, 7004]
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v4

      - name: Clone application repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Deploy service
        uses: ./.github/actions/deploy-service
        with:
          env: ${{ matrix.env }}
          port: ${{ matrix.port }}
          working-directory: python-greetings

  test:
    needs: deploy
    runs-on: self-hosted
    strategy:
      matrix:
        env: [dev, staging, preprod, prod]
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v4

      - name: Clone test framework repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          env: ${{ matrix.env }}
          working-directory: course-js-api-framework
