name: Python Greetings Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Check Python Version
        run: python --version
      - name: Install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Deploy to Dev
        run: echo Deploying to dev on port 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Run tests on Dev
        run: echo Running tests on dev

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Deploy to Staging
        run: echo Deploying to staging on port 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Run tests on Staging
        run: echo Running tests on staging

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Deploy to Preprod
        run: echo Deploying to preprod on port 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Run tests on Preprod
        run: echo Running tests on preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Deploy to Prod
        run: echo Deploying to prod on port 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: Run tests on Prod
        run: echo Running tests on prod
