name: Python Greetings Microservice Delivery Pipeline

on: [push]

jobs:
  install-pip-deps:
    runs-on: [self-hosted]
    steps:
      - name: Install Python Dependencies
        uses: ./.github/actions/install-python-deps

  deploy-to-dev:
    needs: [install-pip-deps]
    runs-on: [self-hosted]
    steps:
      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          env_name: "dev"
          port: "7001"

  tests-on-dev:
    needs: [deploy-to-dev]
    runs-on: [self-hosted]
    steps:
      - name: Run Tests on Dev
        uses: ./.github/actions/test
        with:
          env_name: "dev"

  deploy-to-staging:
    needs: [tests-on-dev]
    runs-on: [self-hosted]
    steps:
      - name: Deploy to Staging
        uses: ./.github/actions/deploy
        with:
          env_name: "staging"
          port: "7002"

  tests-on-staging:
    needs: [deploy-to-staging]
    runs-on: [self-hosted]
    steps:
      - name: Run Tests on Staging
        uses: ./.github/actions/test
        with:
          env_name: "staging"

  deploy-to-preprod:
    needs: [tests-on-staging]
    runs-on: [self-hosted]
    steps:
      - name: Deploy to PreProd
        uses: ./.github/actions/deploy
        with:
          env_name: "preprod"
          port: "7003"

  tests-on-preprod:
    needs: [deploy-to-preprod]
    runs-on: [self-hosted]
    steps:
      - name: Run Tests on PreProd
        uses: ./.github/actions/test
        with:
          env_name: "preprod"

  deploy-to-prod:
    needs: [tests-on-preprod]
    runs-on: [self-hosted]
    steps:
      - name: Deploy to Prod
        uses: ./.github/actions/deploy
        with:
          env_name: "prod"
          port: "7004"

  tests-on-prod:
    needs: [deploy-to-prod]
    runs-on: [self-hosted]
    steps:
      - name: Run Tests on Prod
        uses: ./.github/actions/test
        with:
          env_name: "prod"
