name: Python Greetings CI/CD (Windows)

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        run: git clone https://github.com/mtararujs/python-greetings python-greetings
        shell: pwsh

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          working-directory: python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: windows-latest
    steps:
      - name: Deploy to dev
        uses: ./.github/actions/deploy-service
        with:
          env-name: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: windows-latest
    steps:
      - name: Run tests on dev
        uses: ./.github/actions/run-tests
        with:
          env-name: dev
