name: Python Greetings Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Checkout python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Deploy to dev
        uses: ./.github/actions/deploy-action
        with:
          env_name: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Run tests on dev
        uses: ./.github/actions/test-action
        with:
          env_name: dev

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Deploy to staging
        uses: ./.github/actions/deploy-action
        with:
          env_name: staging
          port: 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Run tests on staging
        uses: ./.github/actions/test-action
        with:
          env_name: staging

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Deploy to preprod
        uses: ./.github/actions/deploy-action
        with:
          env_name: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Run tests on preprod
        uses: ./.github/actions/test-action
        with:
          env_name: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Deploy to prod
        uses: ./.github/actions/deploy-action
        with:
          env_name: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Run tests on prod
        uses: ./.github/actions/test-action
        with:
          env_name: prod
