name: Python Delivery Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        shell: cmd
        working-directory: python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Deploy to Dev
        uses: ./.github/actions/deploy@v1
        with:
          environment: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Run tests on Dev
        uses: ./.github/actions/test@v1
        with:
          environment: dev

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Deploy to Staging
        uses: ./.github/actions/deploy@v1
        with:
          environment: staging
          port: 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Run tests on Staging
        uses: ./.github/actions/test@v1
        with:
          environment: staging

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Deploy to Preprod
        uses: ./.github/actions/deploy@v1
        with:
          environment: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Run tests on Preprod
        uses: ./.github/actions/test@v1
        with:
          environment: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Deploy to Prod
        uses: ./.github/actions/deploy@v1
        with:
          environment: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Run tests on Prod
        uses: ./.github/actions/test@v1
        with:
          environment: prod
